# THopper PRO++ Risk Management Configuration - Production Optimized

# SafeMode Configuration (Maximum Protection)
safe_mode:
  enable_safe_mode: true
  auto_enable: true
  
  # Triggers (AGGRESSIVE protection)
  triggers:
    - ai_error
    - continuous_loss
    - high_atr_spike
    - system_crash
    - api_error
    - insufficient_balance
    - network_timeout
    - low_accuracy
    - high_drawdown
    
  # SafeMode behavior (CONSERVATIVE recovery)
  disable_after_minutes: 360  # 6 hours cooldown
  max_activations_per_day: 2  # Strict limit
  cooldown_period: 180  # 3 hours between activations
  
  # Recovery conditions (STRICT requirements)
  recovery_checks:
    - system_health_ok
    - market_stability
    - model_accuracy_recovered
    - no_recent_errors
    - drawdown_recovered

# Risk Limits (CONSERVATIVE - optimized for consistent profitability)
limits:
  # Portfolio level (STRICT capital protection)
  max_portfolio_risk: 2.5      # % of total capital
  max_daily_loss: 1.5          # % of total capital  
  max_weekly_loss: 4.5         # % of total capital
  max_monthly_loss: 12.0       # % of total capital
  
  # Position level (FOCUSED approach)
  max_position_size: 4.0       # % of portfolio
  max_positions: 2             # QUALITY over quantity
  max_correlation: 0.5         # STRICT diversification
  
  # Trade level (SELECTIVE trading)
  max_trade_size: 1000         # USD per trade
  min_trade_size: 50           # USD minimum
  max_trades_per_hour: 1       # Prevent overtrading
  max_trades_per_day: 3        # Quality focus
  min_time_between_trades: 45  # Minutes - avoid FOMO

# Stop Loss & Take Profit (OPTIMIZED risk/reward)
sl_tp:
  default_sl: 1.8    # % - Conservative stop loss
  default_tp: 5.4    # % - Better risk/reward ratio (3:1)
  max_sl: 3.0        # % - Never risk more than 3%
  min_tp: 3.6        # % - Minimum 2:1 ratio
  
  # Dynamic adjustment (INTELLIGENT stops)
  atr_multiplier_sl: 1.5  # Conservative ATR multiple
  atr_multiplier_tp: 4.5  # Aggressive profit targets
  volatility_adjustment: true
  
  # Trailing stops (PROFIT protection)
  trailing_enabled: true
  trailing_trigger: 2.0   # % profit to activate
  trailing_distance: 0.6  # % trail distance

# Drawdown Protection (CAPITAL preservation)
drawdown:
  max_drawdown: 8.0         # % - STRICT limit
  halt_trading_at: 5.0      # % drawdown to stop
  reduce_position_at: 3.0   # % drawdown to scale down
  position_reduction: 0.5   # Factor to reduce by
  
  recovery_threshold: 1.5   # % profit to resume normal
  monitoring_window: 14     # Days to track drawdown

# Market Condition Filters (QUALITY trade selection)
market_filters:

  # Volatility filters (AVOID choppy markets)

  min_volatility: 0.008     # Minimum daily volatility
  max_volatility: 0.06      # Maximum daily volatility
  
  # Volume filters (LIQUID markets only)
  min_volume: 15000000      # Minimum 24h volume USD
  volume_spike_threshold: 1.8 # Ratio to average volume
  
  # Spread filters (COST efficiency)
  max_spread: 0.002         # Maximum bid-ask spread %
  
  # Market hours (OPTIMAL trading windows)
  trading_hours:
    start: "08:00"
    end: "20:00"
    timezone: "UTC"
    
  # Blackout periods (AVOID risky times)
  blackout:
    major_news: true
    fomc_meetings: true
    weekend_gaps: true
    low_liquidity_hours: true

# Position Sizing (SCIENTIFIC approach)
position_sizing:
  method: kelly               # Kelly criterion
  kelly_fraction: 0.12        # CONSERVATIVE Kelly
  max_kelly: 0.25            # Cap Kelly suggestions
  min_position: 0.5          # % of portfolio minimum
  
  # Risk-adjusted sizing (INTELLIGENT allocation)
  volatility_lookback: 14    # Days
  risk_free_rate: 0.03       # Annual
  target_volatility: 0.12    # Annual target
  
  # Confidence-based sizing (AI-driven)
  confidence_multiplier: 1.2  # Boost high-confidence trades
  min_confidence_size: 0.7    # Minimum confidence for sizing

  # Confidence-based sizing (AI-driven)
  confidence_multiplier: 1.2  # Boost high-confidence trades
  min_confidence_size: 0.7    # Minimum confidence for sizing

# Correlation Management (DIVERSIFICATION)
correlation:
  max_correlation: 0.5      # STRICT correlation limit
  correlation_window: 21    # Days
  rebalance_threshold: 0.6  # Trigger for rebalancing
  
  # Asset groups (AVOID correlated positions)
  groups:
    crypto_majors: [BTCUSDT, ETHUSDT]
    # Only trading majors for now

# Emergency Controls (CIRCUIT breakers)
emergency:
  # Circuit breakers (AUTO protection)
  price_change_limit: 0.15  # % in 5 minutes
  volume_spike_limit: 3.0   # Ratio to average
  
  # Auto-liquidation (LOSS limitation)
  margin_call_threshold: 0.85
  liquidation_threshold: 0.95
  
  # Kill switch (MANUAL override)
  kill_switch_enabled: true
  kill_switch_triggers:
    - system_error
    - api_failure
    - unusual_activity
    - manual_activation

# Monitoring & Alerts (PROACTIVE management)
monitoring:
  real_time_risk: true
  risk_dashboard: true
  alert_frequency: immediate  # No delays on critical alerts
  
  alert_thresholds:
    portfolio_risk: 2.0       # %
    single_position: 3.5      # %
    daily_loss: 1.0           # %
    drawdown: 3.0             # %
    consecutive_losses: 2     # Number of losses
    
  alert_channels:
    - discord
    - dashboard

    # Add email/SMS for critical alerts

# Performance Requirements (PROFITABILITY gates)
performance_gates:
  min_win_rate: 0.60          # Required win rate
  min_profit_factor: 1.3      # Gross profit / gross loss
  min_sharpe_ratio: 1.2       # Risk-adjusted returns
  max_consecutive_losses: 4   # Stop trading threshold
  
  # Review periods (PERFORMANCE evaluation)
  daily_review: true
  weekly_deep_review: true
  monthly_strategy_review: true

# Advanced Risk Features (INTELLIGENT protection)
advanced:
  # Market regime detection (ADAPTIVE risk)
  regime_detection: true
  bear_market_reduction: 0.5  # Reduce positions in bear market
  high_volatility_reduction: 0.7  # Reduce in high vol
  
  # Behavioral risk management (EMOTIONAL protection)
  revenge_trading_protection: true
  fomo_protection: true
  overconfidence_protection: true
  
  # System health integration (TECHNICAL protection)
  api_health_required: true
  model_health_required: true
  data_quality_required: true

# Backtesting Risk Parameters (HISTORICAL validation)
backtesting:
  initial_capital: 10000
  commission: 0.001         # 0.1% per trade
  slippage: 0.0003         # 0.03% slippage
  max_positions_backtest: 2
  rebalance_frequency: daily

  # Stress testing (WORST case scenarios)
  stress_test_scenarios:
    - market_crash
    - flash_crash  
    - api_outage
    - model_failure
