# THopper PRO++ Strategy Configuration - Production Optimized

strategy:
  name: rsi_macd
  timeframe: 1h
  confidence_threshold: 0.78  # Higher for profitability
  tech_weight: 0.4         # Weight of technical signals
  ai_weight: 0.6           # Weight of AI signals
  allowed_side: [buy, sell]
  use_trend_filter: true
  dynamic_sl_tp: true
  sl: 1.8  # Conservative stop loss
  tp: 5.4  # Better risk/reward ratio
  
  trailing:
    enabled: true
    type: pnl
    trigger_pct: 2.0
    trail_pct: 0.6
  
  # Coin Selection (Conservative)
  min_volume_binance: 15000000  # Higher volume for stability
  top_n: 2  # Focus on best opportunities only
  max_workers: 1  # Railway resource optimization
  debug: false
  banned_keywords: [DOWN, UP, BEAR, BULL, TUSD, USDC, BUSD]
  
  # Position Management (Risk-focused)
  max_position_size: 4.0  # Conservative sizing
  position_sizing_method: kelly
  kelly_fraction: 0.12  # Conservative Kelly
  
  # Quality filters (Profitability focused)
  min_signal_strength: strong
  require_trend_confirmation: true
  min_volume_ratio: 1.5
  max_spread_threshold: 0.002
    
# RSI-MACD Strategy (Conservative parameters)
strategies:
  rsi_macd:
    timeframe: 1h
    rsi_period: 21  # Longer period for stability
    rsi_oversold: 20  # More extreme levels
    rsi_overbought: 80
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9

    trend_confirmation: true
    min_trend_strength: 0.6

# Risk Management (Safety-first)
risk_management:
  max_daily_trades: 3  # Quality over quantity
  max_concurrent_positions: 2  # Focus and safety
  portfolio_heat: 2.5  # Conservative exposure
  correlation_limit: 0.5  # Strict diversification
  min_time_between_trades: 45  # Prevent overtrading
  
  # Profitability filters
  min_reward_risk_ratio: 2.5
  min_win_rate_requirement: 0.65
  profit_factor_threshold: 1.4

# 🔄 Danh sách chiến lược được bật
available_strategies:
  - rsi_macd
  - dca_breakout
  - trend_breakout
  - copy_trade
