# THopper PRO++ Webhook Configuration

# Server Settings
server:
  host: 0.0.0.0
  port: 8000
  max_connections: 100
  timeout: 30
  
# Security Settings
security:
  hmac_enabled: true
  require_signature: true
  allowed_sources:
    - tradingview
    - appsheet
    - custom
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst_limit: 10

# Queue Configuration
queue:
  enabled: true
  max_size: 1000
  batch_processing: true
  batch_size: 10
  process_interval: 1  # seconds
  retry_attempts: 3
  retry_delay: 5  # seconds

# Webhook Endpoints
endpoints:
  predict:
    path: /webhook/predict
    method: POST
    enabled: true
    required_fields: [symbol, source, action]
    
  reward:
    path: /webhook/reward  
    method: POST
    enabled: true
    required_fields: [symbol, source, action, reward]
    
  health:
    path: /health
    method: GET
    enabled: true
    auth_required: false

# Processing Rules
processing:
  validate_symbols: true
  allowed_symbols:
    - BTCUSDT
    - ETHUSDT
    - ADAUSDT
    - BNBUSDT
    - SOLUSDT
    - XRPUSDT
    - DOTUSDT
    - LINKUSDT
    - LTCUSDT
    - BCHUSDT
    
  symbol_mapping:
    BTC/USDT: BTCUSDT
    ETH/USDT: ETHUSDT
    ADA/USDT: ADAUSDT
    
  action_handlers:
    predict: handle_prediction_request
    reward: handle_reward_signal
    trade: handle_trade_signal

# Logging
logging:
  enabled: true
  log_requests: true
  log_responses: true
  log_errors: true
  log_file: webhook.log
  log_level: INFO

# Notification Settings
notifications:
  discord_alerts: true
  alert_on_error: true
  alert_on_high_volume: true
  volume_threshold: 50  # requests per minute
